"""Added Sentiment

Revision ID: 6b11613dfb24
Revises: 4c0f50f83df8
Create Date: 2026-02-15 06:43:36.198122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b11613dfb24'
down_revision: Union[str, Sequence[str], None] = '4c0f50f83df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_symbol_date')
    )
    op.create_index(op.f('ix_news_sentiment_date'), 'news_sentiment', ['date'], unique=False)
    op.create_index(op.f('ix_news_sentiment_id'), 'news_sentiment', ['id'], unique=False)
    op.create_index(op.f('ix_news_sentiment_symbol'), 'news_sentiment', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sentiment_symbol'), table_name='news_sentiment')
    op.drop_index(op.f('ix_news_sentiment_id'), table_name='news_sentiment')
    op.drop_index(op.f('ix_news_sentiment_date'), table_name='news_sentiment')
    op.drop_table('news_sentiment')
    # ### end Alembic commands ###
