"""Added Take Profit and removed Con Trade

Revision ID: ff89f9eb4529
Revises: 129dea75d2a0
Create Date: 2026-02-15 11:48:22.792517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff89f9eb4529'
down_revision: Union[str, Sequence[str], None] = '129dea75d2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('take_profit_pct', sa.Float(), nullable=True))
    op.drop_column('watchlist', 'max_concurrent_trades')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('max_concurrent_trades', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('global_settings', 'take_profit_pct')
    # ### end Alembic commands ###
